install.packages("RODBC", repos="https://cloud.r-project.org")
install.packages("ggplot2", repos="https://cloud.r-project.org")
install.packages("ggmap", repos="https://cloud.r-project.org")
install.packages("plyr", repos="https://cloud.r-project.org")
install.packages("forecast", repos="https://cloud.r-project.org")
install.packages("reshape2", repos="https://cloud.r-project.org")
install.packages("spatial", repos="https://cloud.r-project.org")
install.packages("curl", repos="https://cloud.r-project.org")
install.packages("spatial", repos="https://cloud.r-project.org")
install.packages("rjson", repos="https://cloud.r-project.org")
install.packages("crayon", repos="https://cloud.r-project.org")

install.packages("randomforest", repos="https://cloud.r-project.org")
install.packages("e1071", repos="https://cloud.r-project.org")
install.packages("rpart", repos="https://cloud.r-project.org")
install.packages("igraph", repos="https://cloud.r-project.org")
install.packages("nnet", repos="https://cloud.r-project.org")
install.packages("caret", repos="https://cloud.r-project.org")
install.packages("kernlab", repos="https://cloud.r-project.org")
install.packages("glmnet", repos="https://cloud.r-project.org")
install.packages("lars", repos="https://cloud.r-project.org")
install.packages("earth", repos="https://cloud.r-project.org")
install.packages("mboost", repos="https://cloud.r-project.org")


install.packages("RODBC", repos="https://cloud.r-project.org")
install.packages("RgoogleMaps", repos="https://cloud.r-project.org")
install.packages("dplyr", repos="https://cloud.r-project.org")
install.packages("plyr", repos="https://cloud.r-project.org")
install.packages("sparklyr", repos="https://cloud.r-project.org")

